# Generated by Django 3.1.1 on 2020-11-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0005_auto_20201125_0805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
