# Generated by Django 3.1.1 on 2020-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0006_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=50)),
            ],
        ),
    ]
