# Generated by Django 3.1.1 on 2020-11-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0007_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='educational',
            new_name='Education_level',
        ),
    ]
