# Generated by Django 3.1.1 on 2020-11-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0010_auto_20201127_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Male_Acute_Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
