# Generated by Django 3.1.1 on 2020-11-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0012_female_acute_ward_female_rehabilitation_ward_male_rehabilitation_ward_paying_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='female_rehabilitation_ward',
            old_name='patient_name',
            new_name='patient_id',
        ),
    ]
