# Generated by Django 3.1.1 on 2020-12-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0014_auto_20201129_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='female_rehabilitation_ward',
            old_name='patient_id',
            new_name='patient_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.religion'),
        ),
    ]
