# Generated by Django 3.1.1 on 2020-12-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0015_auto_20201202_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.CharField(max_length=15),
        ),
    ]
