# Generated by Django 3.1.1 on 2020-12-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0018_male_rehabilitation_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Female_Rehabilitation_Ward',
        ),
    ]
