# Generated by Django 3.1.1 on 2020-12-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0019_delete_female_rehabilitation_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
