# Generated by Django 3.1.1 on 2020-12-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0022_auto_20201203_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefferalMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_refferal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_reffered_from', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalpsychiatrichistory',
            name='mode_of_refferal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.refferalmode'),
        ),
        migrations.AlterField(
            model_name='medicalpsychiatrichistory',
            name='region_reffered_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.region'),
        ),
    ]
