# Generated by Django 3.1.1 on 2020-12-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0025_auto_20201203_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctornotes',
            old_name='notes',
            new_name='Doctor_notes',
        ),
        migrations.RenameField(
            model_name='nursenotes',
            old_name='notes',
            new_name='Nurse_notes',
        ),
    ]
