# Generated by Django 3.1.1 on 2020-12-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0031_prescriptiondetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionDetail',
            new_name='Prescription',
        ),
    ]
