# Generated by Django 3.1.1 on 2020-12-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0036_auto_20201207_0545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorNotes',
            new_name='DoctorNote',
        ),
    ]
