# Generated by Django 3.1.1 on 2020-12-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0037_auto_20201207_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NurseNotes',
            new_name='NurseNote',
        ),
    ]
