# Generated by Django 3.1.1 on 2020-12-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0038_auto_20201207_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='final_prescription',
            field=models.TextField(max_length=2000),
        ),
    ]
