# Generated by Django 3.1.1 on 2020-12-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0039_auto_20201207_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exit',
            old_name='doctor_id',
            new_name='doctor_name',
        ),
    ]
