# Generated by Django 3.1.1 on 2020-12-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0041_female_rehabilitation_ward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalPsychiatricHistory',
            new_name='MedicalPsychiatricHistorys',
        ),
    ]
