# Generated by Django 3.1.1 on 2020-12-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0043_auto_20201207_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
