# Generated by Django 3.1.1 on 2020-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0044_auto_20201208_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
