# Generated by Django 3.1.1 on 2020-11-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_consultation', models.CharField(max_length=50)),
                ('hospital_in_patient_number', models.IntegerField()),
                ('hospital_OPD_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('tribe', models.CharField(max_length=15)),
                ('marital_status', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=15)),
                ('educational', models.CharField(max_length=20)),
                ('employment', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=20)),
                ('home_village', models.CharField(max_length=20)),
                ('home_TA', models.CharField(max_length=20)),
                ('home_distric', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('name_of_next_of_kin', models.CharField(max_length=30)),
                ('phone_of_guardian', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=50)),
                ('Ward_number', models.IntegerField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='NurseNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=1000)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPsychiatricHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referring_institution', models.CharField(max_length=50)),
                ('last_time_treated_at', models.CharField(max_length=20)),
                ('region_reffered_from', models.CharField(max_length=15)),
                ('mode_of_refferal', models.CharField(max_length=20)),
                ('history_of_mental_illness_in_family', models.CharField(max_length=5)),
                ('history_of_epilepsy', models.CharField(max_length=5)),
                ('date_of_OPD_review', models.DateField()),
                ('type_of_OPD_exit', models.CharField(max_length=25)),
                ('number_of_addmission', models.IntegerField()),
                ('type_of_ward_exit', models.CharField(max_length=50)),
                ('number_of_abscond', models.IntegerField()),
                ('if_transferred_where', models.CharField(max_length=50)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HIVTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HIV_sero_status', models.CharField(max_length=20)),
                ('if_reactive_when_was_tested', models.CharField(max_length=25)),
                ('if_reactive_is_on_HAART', models.CharField(max_length=5)),
                ('indication_for_HAART', models.CharField(max_length=100)),
                ('how_long_on_HAART', models.CharField(max_length=30)),
                ('if_on_HAART_when_initiated', models.CharField(max_length=30)),
                ('if_on_HAART_what_is_regime', models.CharField(max_length=10)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_prescription', models.CharField(max_length=200)),
                ('date_of_exit', models.DateField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.employee')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=1000)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychiatric', models.CharField(max_length=50)),
                ('medical', models.CharField(max_length=50)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('comments', models.TextField(max_length=500)),
                ('services', models.TextField(max_length=500)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.employee')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
    ]
