# Generated by Django 3.1.1 on 2020-11-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0002_auto_20201125_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_district', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.districts'),
        ),
    ]
