# Generated by Django 3.1.1 on 2020-11-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0004_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Education_Level',
            new_name='education_Level',
        ),
    ]
