# Generated by Django 3.1.1 on 2020-11-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0011_auto_20201127_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paying_Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Male_Rehabilitation_Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Female_Rehabilitation_Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Female_Acute_Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
    ]
