# Generated by Django 3.1.1 on 2020-11-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0013_auto_20201127_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital_OPD_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_in_patient_number',
        ),
    ]
