# Generated by Django 3.1.1 on 2020-12-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0016_auto_20201202_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Male_Rehabilitation_Ward',
        ),
    ]
