# Generated by Django 3.1.1 on 2020-12-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0023_auto_20201203_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='HAARTDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_long_on_HAART', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HAARTIndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication_for_HAART', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HAARTRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_on_HAART_what_is_regime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HIVStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HIV_sero_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='hivtest',
            name='HIV_sero_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.hivstatus'),
        ),
        migrations.AlterField(
            model_name='hivtest',
            name='how_long_on_HAART',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.haartduration'),
        ),
        migrations.AlterField(
            model_name='hivtest',
            name='if_on_HAART_what_is_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.haartregime'),
        ),
        migrations.AlterField(
            model_name='hivtest',
            name='indication_for_HAART',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.haartindication'),
        ),
    ]
