# Generated by Django 3.1.1 on 2020-12-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0026_auto_20201203_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PsychiatricDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Psychiatric', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.medicaldiagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='psychiatric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.psychiatricdiagnosis'),
        ),
    ]
