# Generated by Django 3.1.1 on 2020-12-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0029_auto_20201204_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
