# Generated by Django 3.1.1 on 2020-12-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0032_auto_20201204_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription',
            new_name='Patient_prescription',
        ),
    ]
