# Generated by Django 3.1.1 on 2020-12-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0033_auto_20201205_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
