# Generated by Django 3.1.1 on 2020-12-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0034_delete_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_name', models.TextField(max_length=2000)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentcare.patient')),
            ],
        ),
    ]
