# Generated by Django 3.1.1 on 2020-12-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0042_auto_20201207_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=3000)),
                ('General_Report', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalpsychiatrichistorys',
            name='history_of_epilepsy',
            field=models.CharField(max_length=35),
        ),
    ]
