# Generated by Django 3.1.1 on 2020-12-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0045_auto_20201208_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
